[tool.black]
line-length = 88
exclude = '''
(
    /stubs/
  | /data/legacy/
  | /.venv/
)
'''

[tool.isort]
profile = "black"
skip = ["stubs/", "data/legacy", ".venv/"]

[tool.ruff]
# チェックしたいルールをお好みで（例として E:エラー, F:フォーマット, I:インポート）
lint.select = ["E", "F", "I"]
# 自動修正を有効に
fix = true

# ルールの除外設定
include = ["core/", "tests/", "llm/", "plugins/", "tools/"]
exclude = ["stubs/", "data/legacy", ".venv/"]
