from antlr4 import *
from antlr4.Token import CommonToken as CommonToken
from typing import TextIO

class LuaLexerBase(Lexer):
    start_line: int
    start_col: int
    def __init__(self, input: InputStream, output: TextIO = ...) -> None: ...
    def HandleComment(self) -> None: ...
    def read_long_string(self, cs: InputStream, sep: int): ...
    def skip_sep(self, cs: InputStream): ...
    def IsLine1Col0(self): ...
