from luaparser.astnodes import *
from luaparser.utils.visitor import *
from _typeshed import Incomplete
from enum import Enum
from multimethod import multimethod as multimethod

class Style(Enum):
    PYTHON = 1
    HTML = 2

class PythonStyleVisitor:
    indentValue: Incomplete
    currentIndent: int
    def __init__(self, indent) -> None: ...
    def indent_str(self, newLine: bool = True): ...
    def indent(self) -> None: ...
    def dedent(self) -> None: ...
    @staticmethod
    def pretty_count(node, is_list: bool = False): ...

escape_dict: Incomplete

def raw(text): ...

class HTMLStyleVisitor:
    def __init__(self) -> None: ...
    def get_xml_string(self, tree): ...

class LuaOutputVisitor:
    def __init__(self, indent_size: int) -> None: ...
    def do_visit(self, node: Node) -> str: ...
