name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      - run: pip install black isort ruff
      - run: black . --check
      - run: isort . --check
      - run: ruff check .
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check types
        run: mypy ./

      - name: Run fetcher.sh (bash)
        run: bash data/fetcher.sh

      - name: Build all (core.loader)
        run: python -m core.loader build-all

      - name: Run pytest
        run: pytest
